### ISSUE TITLE
Update electron to 1.6.1

### ISSUE THREAD

**Issue by black-snow** [szwacz/electron-boilerplate#256]
We're currently using `1.4.7^` - an upgrade to 1.6.1 (current stable as of writing this) would be nice. There were quite some additions in the meantime and a lot of v8 improvements, I think.

This ticket is here to keep track of the progress.
Guess I'll be able to work on this later this week.

**TODO:**
- [x] check for backward incompatibilities 1.4 => 1.5
- [x] check for backward incompatibilities 1.5 => 1.6
- [x] update to 1.6 & run tests
- [x] 1.6 check for incompatibilities w/ other libs (mocha etc.) - maybe upgrade them, too
- [x] 1.6 PR
- [x] 1.6 builds on all platforms
- [x] 1.6 merge

---

No, wait. The electron homepage lists 1.6.1 but it's still beta if you look at the releases on github. 1.5.x is still in beta, too. Latest stable is `v1.4.15` (which we're using implicitly).
So I guess I'll have to stall this ticket.

**Comment by szwacz** [comment]
Indeed electron 1.4 is still the main release visible in npm: https://www.npmjs.com/package/electron
so it's too early. But surely PR will be greatly appreciated when 1.6 is out :)

**Comment by black-snow** [comment]
Guess I'll make a 1.5 and a 1.6 branch, then. So that it's ready when it's stable :)

**Comment by black-snow** [comment]
Seems like they have skipped 1.5 and are now on 1.6.1. Guess I'll drop my 1.5 branch then and do a 1.6.

**Comment by black-snow** [comment]
PR filed [here](https://github.com/szwacz/electron-boilerplate/pull/257). @szwacz 

There are a couple possible breaking changes for rollup, electron-builder and fs-jetpack.
Do people actually update the boilerplate for existing projects? I do :)

@szwacz Can we kick out rollup? Electron 1.6 ships with native imports and async/await which, I guess, collides with rollup or rather makes it obsolete.

**Comment by szwacz** [comment]
Thanks @black-snow! I fell behind a bit in the electron world, will get back to speed and test you PR today or tomottow.

About dropping rollup - this is complicated. Even if native imports will finally be shipped to electron still a lot (all?) modern web frameworks utilize heavily compiling tools (Rect and Vue for sure), and people using those frameworks are no good without some transpilation pipeline. This is topic for research.

**Comment by black-snow** [comment]
You're welcome.
Guess we can't drop rollup anytime soon.

Anyaway, I'm having another issue with *rollup*. I can't use async/await in my code. *rollup* complains that `await` is some kind of reserved keyword and won't process the sources. I haven't yet found a fix.

To reproduce, add this to your background.js and try to `npm start` the thing.

```js
async function test(){
  let b = await testP()
  console.log(b)
}

function testP(){
  return new Promise((resolve, reject) => {
    window.setTimeout(() => resolve('ok'), 500)
  })
}

// somewhere in the app-started body
test()
```

**Comment by szwacz** [comment]
@black-snow there are some problems after updating (`npm run release` on mac is failing). Could you please address this PR to branch `elecron-1.6`? Then well be able to merge it and troubleshoot the problems one by one.

**Comment by szwacz** [comment]
Crap! I wanted to close PR, not the issue :)

**Comment by szwacz** [comment]
About the async-await problems. This issue states that it should work: https://github.com/rollup/rollup/issues/347

About dropping rollup. As you said it's not that easy, and a lot of people will use traspilation pipeline aywa. So I'd like to make the boilerplate so you can easily delete `src` folder and write all your code in `app` folder it this is your preferred way. But native `import` support need to be shipped first.

**Comment by black-snow** [comment]
@szwacz do you know what `acorn` is? I've already read the issue that you've posted but it rather confused me 😕

**Comment by szwacz** [comment]
Introduced one small fix. Tested. Works. Merged to master :)
